# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0002_auto_20161006_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='itemid',
            new_name='itemz',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='userid',
            new_name='userz',
        ),
    ]
